function [Ensemble,nbins,binsize,Heading,Pitch,Roll,Lat,Long] = import_ebhprll(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [ENSEMBLE,NBINS,BINSIZE,HEADING,PITCH,ROLL,LAT,LONG] =
%   IMPORTFILE(FILENAME) Reads data from text file FILENAME for the default
%   selection.
%
%   [ENSEMBLE,NBINS,BINSIZE,HEADING,PITCH,ROLL,LAT,LONG] =
%   IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Ensemble,nbins,binsize,Heading,Pitch,Roll,Lat,Long] = import_ebhprll('A2_J_0_000_19-06-09_132346_trial_beam2details_template_new_ASC.TXT',1, 606);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/07/03 11:36:19

%% Initialize variables.
delimiter = {',',' '};
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column3: double (%f)
%   column5: double (%f)
%	column7: double (%f)
%   column9: double (%f)
%	column11: double (%f)
%   column13: double (%f)
%	column15: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%*s%f%*s%f%*s%f%*s%f%*s%f%*s%f%*s%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Ensemble = dataArray{:, 1};
nbins = dataArray{:, 2};
binsize = dataArray{:, 3};
Heading = dataArray{:, 4};
Pitch = dataArray{:, 5};
Roll = dataArray{:, 6};
Lat = dataArray{:, 7};
Long = dataArray{:, 8};



