function biM=threeBsol(errorbeam,conv,alpha)
        a=1/(2*sind(alpha));
        b=1/(4*cosd(alpha));
        
             % compute three-beam solution
            if errorbeam==1 % beam 1
                biM = [0,-2*a*conv,a*conv,a*conv;...
                    0,0,-a*conv,a*conv;...
                    0,0,2*b,2*b;...
                    0,0,0,0];
            elseif errorbeam==2
                biM = [2*a*conv,0,-a*conv,-a*conv;...
                    0,0,-a*conv,a*conv;...
                    0,0,2*b,2*b;...
                    0,0,0,0];
            elseif errorbeam==3
                biM = [a*conv,-a*conv,0,0;...
                    -a*conv,-a*conv,0,2*a*conv;...
                    2*b,2*b,0,0;...
                    0,0,0,0];
            elseif errorbeam==4
                biM = [a*conv,-a*conv,0,0;...
                    a*conv,a*conv,-2*a*conv,0;...
                    2*b,2*b,0,0;...
                    0,0,0,0];
            end
end